# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyDating' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'CryptoSwift'
  pod 'SQLite.swift', '~> 0.11.2'
  use_frameworks!
  # Pods for SwiftyDating

  target 'SwiftyDatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyDatingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
